version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Jakarta"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Jakarta"
    versioning-strategy: lockfile-only
    groups:
      dependencies:
        patterns: ['*']
