name: Release

on:
  push:
    branches:
      - master
    paths:
      - packages/*/package.json

jobs:
  github:
    name: Publish to GitHub
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'

    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn publish:packages -y --registry 'https://npm.pkg.github.com'

  npm:
    name: Publish to NPM
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn publish:packages -y --registry 'https://registry.npmjs.org'

